// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkdp8o_NwlaEO36j6aAznWb7j_jo3CYM8',
    appId: '1:748924248614:web:c7f5647c2c1d2e6c64bce7',
    messagingSenderId: '748924248614',
    projectId: 'fiyatalarm-fe764',
    authDomain: 'fiyatalarm-fe764.firebaseapp.com',
    storageBucket: 'fiyatalarm-fe764.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApYqTfxneVcRMBNZ8_MmGcjcLpR2zXLMQ',
    appId: '1:748924248614:android:b2ee4b4d9937211e64bce7',
    messagingSenderId: '748924248614',
    projectId: 'fiyatalarm-fe764',
    storageBucket: 'fiyatalarm-fe764.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkdp8o_NwlaEO36j6aAznWb7j_jo3CYM8',
    appId: '1:748924248614:web:171942a3e0e911d064bce7',
    messagingSenderId: '748924248614',
    projectId: 'fiyatalarm-fe764',
    authDomain: 'fiyatalarm-fe764.firebaseapp.com',
    storageBucket: 'fiyatalarm-fe764.firebasestorage.app',
  );
}
